# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5258e7cd1ffa0cb581876239ce5940c1b5663c1ad39d96223b174f4babba8addff022c8f497d1ee0be1086a16bfefc09cb4c0b3e8e3fa101aadd0abea3fd95d

test:
  secret_key_base: 2bdff8975f7db59bc411d55294e866a5a57520f30a25b6fde553b4cc33a0d26758654b3e7d4f79a76a49be4737b423a244282b46ca5c53cf32df1f6e30975efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
